export const dummyArray = [
  [
    12299,
    811,
    "Bang Bang Buffalo Shrimp",
    "Buffalo shrimp, paired with a vegetable.",
    "Shrimp, buffalo sauce, vegetable",
    3,
    1,
    70,
    375,
    12,
    3,
    3,
    21,
    159,
  ],
  [
    12302,
    806,
    "BBQ Marinated Steak",
    "BBQ Steak, paired with a vegetable.",
    "Angus chuck tender, BBQ sauce, vegetable",
    9,
    1,
    80,
    370,
    14,
    3,
    6,
    27,
    245,
  ],
  [
    12354,
    822,
    "Cajun Salmon",
    "Cajun salmon, paired with a vegetable.",
    "Salmon, cajun seasoning, vegetable",
    12,
    2,
    40,
    525,
    12,
    3,
    3,
    22,
    244,
  ],
  [
    12364,
    803,
    "Chicken Stir Fry",
    "Chicken, paired with a vegetable, topped with peppers, onions, and teriyaki sauce.",
    "Chicken breast, peppers, onions, teriyaki sauce, vegetable",
    2,
    0,
    35,
    455,
    15,
    3,
    9,
    29,
    194,
  ],
  [
    12378,
    819,
    "Flex on Me Grilled Chicken",
    "Grilled chicken, topped with a jala mango sauce, served with a vegetable.",
    "Grilled chicken, jala mango sauce, vegetable",
    8,
    0,
    35,
    340,
    13,
    3,
    7,
    26,
    228,
  ],
  [
    12475,
    802,
    "Pulled BBQ Chicken",
    "Pulled BBQ chicken, paired with a vegetable",
    "Chicken breast, BBQ sauce, vegetables",
    2,
    0,
    35,
    325,
    15,
    3,
    9,
    26,
    182,
  ],
  [
    12491,
    821,
    "Signature Burger - How You Doin?",
    "Our beef burger, Served with a vegetable, topped with mozzarella, roasted red peppers, balsamic glaze.",
    "Ground beef, bread crumb salt, pepper, mozzarella, roasted red peppers, balsamic glaze, vegetable",
    24,
    5,
    45,
    385,
    12,
    3,
    7,
    26,
    368,
  ],
  [
    12493,
    820,
    "Signature Burger Merica Smokehouse",
    "Our beef burger, Served with a vegetable, topped with american cheese, turkey bacon, and BBQ sauce.",
    "Ground beef, bread crumb salt, pepper, american cheese, turkey bacon, bbq sauce, vegetable",
    24,
    4,
    90,
    410,
    14,
    3,
    9,
    27,
    380,
  ],
  [
    12492,
    807,
    "Signature Burger Buffalo Wolverine",
    "Our beef burger, Served with a vegetable, topped with blue cheese and buffalo ranch sauce.",
    "Ground beef, bread crumb salt, pepper, blue cheese, buffalo, ranch, vegetable",
    26,
    4,
    35,
    485,
    12,
    3,
    6,
    25,
    382,
  ],
  [
    12504,
    814,
    "Steak Stir Fry",
    "Steak, paired with a vegetable, topped with peppers, onions, and teriyaki sauce.",
    "Angus chuck tender, peppers, onions, teriyaki sauce, vegetable",
    9,
    1,
    80,
    370,
    15,
    3,
    9,
    27,
    249,
  ],
  [
    12507,
    815,
    "Steak, Mashed & Gravy",
    "Steak, Served with a vegetable, topped with gravy",
    "Angus chuck tender, brown gravy, vegetable",
    9,
    1,
    55,
    385,
    12,
    3,
    6,
    27,
    237,
  ],
  [
    12522,
    "812-1",
    'Swole Nuggs -  "The General" Tso',
    "Breaded chicken tenders, served with a vegetable and topped with our general tso sauce.",
    "Chicken tenders, breadcrumb, vegetable, general tso sauce",
    3,
    1,
    75,
    425,
    14,
    4,
    9,
    27,
    191,
  ],
  [
    12525,
    810,
    "Swole Nuggs - Buffalo Ranch",
    "Breaded chicken tenders, served with a vegetable and topped with our buffalo ranch sauce.",
    "Chicken tenders, breadcrumb, vegetable, buffalo, ranch",
    9,
    1,
    60,
    500,
    16,
    4,
    7,
    27,
    253,
  ],
  [
    12531,
    809,
    "Swole Nuggs - Parmesan Garlic",
    "Breaded chicken tenders, served with a vegetable and topped with our parmesan garlic sauce.",
    "Chicken tenders, breadcrumb, vegetable, parmesan garlic sauce",
    10,
    3,
    35,
    495,
    14,
    4,
    7,
    28,
    258,
  ],
  [
    12534,
    812,
    "Swole Nuggs - Sweet Chili",
    "Breaded chicken tenders, served with a vegetable and topped with our sweet chili sauce",
    "Chicken tenders, breadcrumb, vegetable, sweet chili sauce",
    14,
    2,
    45,
    455,
    14,
    4,
    9,
    27,
    290,
  ],
  [
    12537,
    808,
    "Swole Nuggs - Sweet Teriyaki",
    "Breaded chicken tenders, served with a vegetable and topped with our teriyaki sauce.",
    "Chicken tenders, breadcrumb, vegetable, teriyaki sauce",
    2,
    0,
    35,
    470,
    16,
    4,
    9,
    27,
    190,
  ],
  [
    12528,
    813,
    "Swole Nuggs - Chicken Parmesan",
    "Breaded chicken tenders, served with a vegetable, topped with mozzarella and marinara sauce",
    "Chicken tenders, breadcrumb, vegetable, mozzarella cheese, tomato sauce",
    10,
    2,
    35,
    415,
    14,
    4,
    7,
    29,
    262,
  ],
  [
    12566,
    804,
    "Teriyaki Grilled Salmon",
    "Teriyaki salmon, paired with a vegetable.",
    "Salmon, teriyaki sauce, vegetable",
    11,
    2,
    55,
    475,
    15,
    3,
    9,
    24,
    255,
  ],
];
